name: "Keystatic"
tagline: ""
description: "Farhan Munim is a seasoned analyst and developer based in London, UK."
logo: ""
favicon: "/uploads/site/favicon.png"
share_image: "/uploads/site/banner.png"
footer_text: "© 2026 Farhan Munim"
social:
  - platform: "GitHub"
    url: "https://github.com/farhanmunim"
    handle: ""
  - platform: "LinkedIn"
    url: "https://linkedin.com/in/farhanmunim"
    handle: ""
  - platform: "YouTube"
    url: "https://youtube.com/@farhan-app"
    handle: ""
  - platform: "Buy Me a Coffee"
    url: "https://buymeacoffee.com/farhan.app"
    handle: ""
analytics_url: ""
noindex: true
head_html: "<script defer src=\"https://mochi.farhan.app/script.js\" data-website-id=\"9a60818f-ad69-4a68-94b4-cf617f22ad81\"></script>"
footer_html: ""
